steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Production build started on $(date)"
    echo "GITHUB TOKEN is $$GITHUB_TOKEN"
    
    # Build the Docker image with all necessary environment variables
    docker build -f ./docker/app.Dockerfile -t asia-south1-docker.pkg.dev/pulse-energy-prod/247-workforce-sim/247-workforce-sim:$SHORT_SHA \
      --build-arg GITHUB_TOKEN=$$GITHUB_TOKEN \
      --build-arg DATABASE_URL=$$DATABASE_URL \
      --build-arg BETTER_AUTH_URL=$$BETTER_AUTH_URL \
      --build-arg BETTER_AUTH_SECRET=$$BETTER_AUTH_SECRET \
      --build-arg ENCRYPTION_KEY=$$ENCRYPTION_KEY \
      --build-arg INTERNAL_API_SECRET=$$INTERNAL_API_SECRET \
      --build-arg POSTGRES_URL=$$POSTGRES_URL \
      --build-arg STRIPE_SECRET_KEY=$$STRIPE_SECRET_KEY \
      --build-arg STRIPE_WEBHOOK_SECRET=$$STRIPE_WEBHOOK_SECRET \
      --build-arg STRIPE_FREE_PRICE_ID=$$STRIPE_FREE_PRICE_ID \
      --build-arg STRIPE_PRO_PRICE_ID=$$STRIPE_PRO_PRICE_ID \
      --build-arg STRIPE_TEAM_PRICE_ID=$$STRIPE_TEAM_PRICE_ID \
      --build-arg STRIPE_ENTERPRISE_PRICE_ID=$$STRIPE_ENTERPRISE_PRICE_ID \
      --build-arg RESEND_API_KEY=$$RESEND_API_KEY \
      --build-arg EMAIL_DOMAIN=$$EMAIL_DOMAIN \
      --build-arg OPENAI_API_KEY=$$OPENAI_API_KEY \
      --build-arg OPENAI_API_KEY_1=$$OPENAI_API_KEY_1 \
      --build-arg OPENAI_API_KEY_2=$$OPENAI_API_KEY_2 \
      --build-arg OPENAI_API_KEY_3=$$OPENAI_API_KEY_3 \
      --build-arg MISTRAL_API_KEY=$$MISTRAL_API_KEY \
      --build-arg ANTHROPIC_API_KEY_1=$$ANTHROPIC_API_KEY_1 \
      --build-arg ANTHROPIC_API_KEY_2=$$ANTHROPIC_API_KEY_2 \
      --build-arg ANTHROPIC_API_KEY_3=$$ANTHROPIC_API_KEY_3 \
      --build-arg FREESTYLE_API_KEY=$$FREESTYLE_API_KEY \
      --build-arg TELEMETRY_ENDPOINT=$$TELEMETRY_ENDPOINT \
      --build-arg COST_MULTIPLIER=$$COST_MULTIPLIER \
      --build-arg JWT_SECRET=$$JWT_SECRET \
      --build-arg BROWSERBASE_API_KEY=$$BROWSERBASE_API_KEY \
      --build-arg BROWSERBASE_PROJECT_ID=$$BROWSERBASE_PROJECT_ID \
      --build-arg OLLAMA_URL=$$OLLAMA_URL \
      --build-arg SENTRY_ORG=$$SENTRY_ORG \
      --build-arg SENTRY_PROJECT=$$SENTRY_PROJECT \
      --build-arg SENTRY_AUTH_TOKEN=$$SENTRY_AUTH_TOKEN \
      --build-arg REDIS_URL=$$REDIS_URL \
      --build-arg AWS_REGION=$$AWS_REGION \
      --build-arg AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID \
      --build-arg AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY \
      --build-arg S3_BUCKET_NAME=$$S3_BUCKET_NAME \
      --build-arg S3_LOGS_BUCKET_NAME=$$S3_LOGS_BUCKET_NAME \
      --build-arg S3_KB_BUCKET_NAME=$$S3_KB_BUCKET_NAME \
      --build-arg AZURE_ACCOUNT_NAME=$$AZURE_ACCOUNT_NAME \
      --build-arg AZURE_ACCOUNT_KEY=$$AZURE_ACCOUNT_KEY \
      --build-arg AZURE_CONNECTION_STRING=$$AZURE_CONNECTION_STRING \
      --build-arg AZURE_STORAGE_CONTAINER_NAME=$$AZURE_STORAGE_CONTAINER_NAME \
      --build-arg AZURE_STORAGE_KB_CONTAINER_NAME=$$AZURE_STORAGE_KB_CONTAINER_NAME \
      --build-arg CRON_SECRET=$$CRON_SECRET \
      --build-arg FREE_PLAN_LOG_RETENTION_DAYS=$$FREE_PLAN_LOG_RETENTION_DAYS \
      --build-arg NODE_ENV=$$NODE_ENV \
      --build-arg ELEVENLABS_API_KEY=$$ELEVENLABS_API_KEY \
      --build-arg AZURE_OPENAI_ENDPOINT=$$AZURE_OPENAI_ENDPOINT \
      --build-arg AZURE_OPENAI_API_VERSION=$$AZURE_OPENAI_API_VERSION \
      --build-arg GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID \
      --build-arg GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET \
      --build-arg GITHUB_CLIENT_ID=$$GITHUB_CLIENT_ID \
      --build-arg GITHUB_CLIENT_SECRET=$$GITHUB_CLIENT_SECRET \
      --build-arg GITHUB_REPO_CLIENT_ID=$$GITHUB_REPO_CLIENT_ID \
      --build-arg GITHUB_REPO_CLIENT_SECRET=$$GITHUB_REPO_CLIENT_SECRET \
      --build-arg X_CLIENT_ID=$$X_CLIENT_ID \
      --build-arg X_CLIENT_SECRET=$$X_CLIENT_SECRET \
      --build-arg CONFLUENCE_CLIENT_ID=$$CONFLUENCE_CLIENT_ID \
      --build-arg CONFLUENCE_CLIENT_SECRET=$$CONFLUENCE_CLIENT_SECRET \
      --build-arg JIRA_CLIENT_ID=$$JIRA_CLIENT_ID \
      --build-arg JIRA_CLIENT_SECRET=$$JIRA_CLIENT_SECRET \
      --build-arg AIRTABLE_CLIENT_ID=$$AIRTABLE_CLIENT_ID \
      --build-arg AIRTABLE_CLIENT_SECRET=$$AIRTABLE_CLIENT_SECRET \
      --build-arg SUPABASE_CLIENT_ID=$$SUPABASE_CLIENT_ID \
      --build-arg SUPABASE_CLIENT_SECRET=$$SUPABASE_CLIENT_SECRET \
      --build-arg NOTION_CLIENT_ID=$$NOTION_CLIENT_ID \
      --build-arg NOTION_CLIENT_SECRET=$$NOTION_CLIENT_SECRET \
      --build-arg DISCORD_CLIENT_ID=$$DISCORD_CLIENT_ID \
      --build-arg DISCORD_CLIENT_SECRET=$$DISCORD_CLIENT_SECRET \
      --build-arg MICROSOFT_CLIENT_ID=$$MICROSOFT_CLIENT_ID \
      --build-arg MICROSOFT_CLIENT_SECRET=$$MICROSOFT_CLIENT_SECRET \
      --build-arg HUBSPOT_CLIENT_ID=$$HUBSPOT_CLIENT_ID \
      --build-arg HUBSPOT_CLIENT_SECRET=$$HUBSPOT_CLIENT_SECRET \
      --build-arg LINEAR_CLIENT_ID=$$LINEAR_CLIENT_ID \
      --build-arg LINEAR_CLIENT_SECRET=$$LINEAR_CLIENT_SECRET \
      --build-arg SLACK_CLIENT_ID=$$SLACK_CLIENT_ID \
      --build-arg SLACK_CLIENT_SECRET=$$SLACK_CLIENT_SECRET \
      --build-arg SOCKET_SERVER_URL=$$SOCKET_SERVER_URL \
      --build-arg SOCKET_PORT=$$SOCKET_PORT \
      --build-arg PORT=$$PORT \
      --build-arg WHITELABEL_APP_NAME=$$WHITELABEL_APP_NAME \
      --build-arg WHITELABEL_APP_DESCRIPTION=$$WHITELABEL_APP_DESCRIPTION \
      --build-arg WHITELABEL_COMPANY_NAME=$$WHITELABEL_COMPANY_NAME \
      --build-arg WHITELABEL_PRIMARY_COLOR=$$WHITELABEL_PRIMARY_COLOR \
      --build-arg WHITELABEL_SECONDARY_COLOR=$$WHITELABEL_SECONDARY_COLOR \
      --build-arg WHITELABEL_APP_URL=$$WHITELABEL_APP_URL \
      --build-arg WHITELABEL_DOCS_URL=$$WHITELABEL_DOCS_URL \
      --build-arg WHITELABEL_SUPPORT_URL=$$WHITELABEL_SUPPORT_URL \
      --build-arg WHITELABEL_TWITTER_HANDLE=$$WHITELABEL_TWITTER_HANDLE \
      --build-arg WHITELABEL_GITHUB_URL=$$WHITELABEL_GITHUB_URL \
      --build-arg WHITELABEL_DISCORD_URL=$$WHITELABEL_DISCORD_URL \
      --build-arg WHITELABEL_ENABLE_TELEMETRY=$$WHITELABEL_ENABLE_TELEMETRY \
      --build-arg WHITELABEL_ENABLE_ANALYTICS=$$WHITELABEL_ENABLE_ANALYTICS \
      --build-arg WHITELABEL_ENABLE_MARKETPLACE=$$WHITELABEL_ENABLE_MARKETPLACE \
      --build-arg WHITELABEL_CUSTOM_LOGO_URL=$$WHITELABEL_CUSTOM_LOGO_URL \
      --build-arg WHITELABEL_CUSTOM_FAVICON_URL=$$WHITELABEL_CUSTOM_FAVICON_URL \
      --build-arg WHITELABEL_CUSTOM_EMAIL_TEMPLATE=$$WHITELABEL_CUSTOM_EMAIL_TEMPLATE \
      --build-arg NEXT_PUBLIC_APP_URL=$$NEXT_PUBLIC_APP_URL \
      --build-arg NEXT_PUBLIC_VERCEL_URL=$$NEXT_PUBLIC_VERCEL_URL \
      --build-arg NEXT_PUBLIC_SENTRY_DSN=$$NEXT_PUBLIC_SENTRY_DSN \
      --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=$$NEXT_PUBLIC_GOOGLE_CLIENT_ID \
      --build-arg NEXT_PUBLIC_GOOGLE_API_KEY=$$NEXT_PUBLIC_GOOGLE_API_KEY \
      --build-arg NEXT_PUBLIC_GOOGLE_PROJECT_NUMBER=$$NEXT_PUBLIC_GOOGLE_PROJECT_NUMBER \
      --build-arg NEXT_PUBLIC_SOCKET_URL=$$NEXT_PUBLIC_SOCKET_URL \
      --build-arg DOCKER_BUILD=true \
      .

  secretEnv: ['GITHUB_TOKEN']

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/pulse-energy-prod/247-workforce-sim/247-workforce-sim:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'prod-247-workforce-sim'  # Your Cloud Run service name
    - '--image'
    - 'asia-south1-docker.pkg.dev/pulse-energy-prod/247-workforce-sim/247-workforce-sim:$SHORT_SHA'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--port'
    - '3000'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '4'
    - '--max-instances'
    - '50'
    - '--min-instances'
    - '1'
    - '--timeout'
    - '300'
    - '--concurrency'
    - '80'
    - '--set-env-vars'
    - 'NODE_ENV=production'
    - '--allow-unauthenticated'

# Step 4: Route 100% traffic to the latest revision
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args:
    - 'run'
    - 'services'
    - 'update-traffic'
    - 'prod-247-workforce-sim'
    - '--to-latest'
    - '--region'
    - 'asia-south1'

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 508073074780@cloudbuild.gserviceaccount.com
availableSecrets:
  secretManager:
  - versionName: projects/508073074780/secrets/GITHUB_TOKEN_CLOUD_BUILD/versions/latest
    env: 'GITHUB_TOKEN' 