steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Build started on $(date)"
    echo "GITHUB TOKEN is $$GITHUB_TOKEN"
    
    # Build the Docker image with essential environment variables
    docker build -f ./docker/app.Dockerfile -t asia-south1-docker.pkg.dev/pulse-energy/pulse-247-workforce/pulse-247-workforce:$SHORT_SHA \
      --build-arg GITHUB_TOKEN=$$GITHUB_TOKEN \
      --build-arg DATABASE_URL=${_DATABASE_URL} \
      --build-arg BETTER_AUTH_URL=${_BETTER_AUTH_URL} \
      --build-arg BETTER_AUTH_SECRET=${_BETTER_AUTH_SECRET} \
      --build-arg ENCRYPTION_KEY=${_ENCRYPTION_KEY} \
      --build-arg NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL} \
      --build-arg DOCKER_BUILD=true \
      .

  secretEnv: ['GITHUB_TOKEN']

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/pulse-energy/pulse-247-workforce/pulse-247-workforce:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'pulse-247-workforce'  # Your Cloud Run service name
    - '--image'
    - 'asia-south1-docker.pkg.dev/pulse-energy/pulse-247-workforce/pulse-247-workforce:$SHORT_SHA'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'

# Step 4: Route 100% traffic to the latest revision
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args:
    - 'run'
    - 'services'
    - 'update-traffic'
    - 'pulse-247-workforce'
    - '--to-latest'
    - '--region'
    - 'asia-south1'

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: 508073074780@cloudbuild.gserviceaccount.com
availableSecrets:
  secretManager:
  - versionName: projects/508073074780/secrets/GITHUB_TOKEN_CLOUD_BUILD/versions/latest
    env: 'GITHUB_TOKEN' 